version: '3'
services:
    lamp:
        image: mattrayner/lamp:latest
        networks:
            - mynet
        ports:
            - 80:80
        volumes:
            - .:/var/www/html:z
        environment:
            TZ: "Europe/Moscow"
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        
    tarantool:
        image: tarantool/tarantool:1.7
        networks:
            - mynet
        volumes:
            - ./tarantool/app.lua:/opt/tarantool
        ports:
            - 3302:3302
        command: tarantool /opt/tarantool/app.lua
        
networks:
    mynet:
        driver: bridge